### ISSUE TITLE
"Get Objects by Layer" node and all Rhinoceros > Geometry nodes to handle lists

### ISSUE THREAD

**Issue by djsiroky** [ksobon/MantisShrimp#16]
The Get Objects by Layer node only accepts a single layer. Also, if giving any of the RH > DS a list of lists, the function will only output the first item from the first list.

**Comment by ksobon** [comment]
I added the multiple layer handling to Get Objects by Layer. Now, that returns a nested list so it is a totally valid addition to add handling of both a list and nested list for the rest of the objects. I am on it. Thanks for posting.

**Comment by ksobon** [comment]
Done! Look for it in the Package Manager or just use the code from here to update nodes as necessary if you want it ASAP.
