### ISSUE TITLE
Select Rhino Geometry does not translate into DS Geometry

### ISSUE THREAD

**Issue by jluebker** [ksobon/MantisShrimp#18]
@ksobon, i'm finding a few instances where some Rhino geometry does not translate into DS geometry by any of the conversion methods. so far i've only seen this happening with select Breps. I am able to bring them into dynamo using an SAT import though. 

I've attached a screen shot of the issue as well as the rhino file, sat file and dynamo file im using.

![ms-bug](https://cloud.githubusercontent.com/assets/4041748/13036603/8e61b9d0-d320-11e5-8c90-aa1d8a72c198.PNG)

[MS-Breps.zip](https://github.com/ksobon/MantisShrimp/files/129927/MS-Breps.zip)

**Comment by ksobon** [comment]
I will have a look at this...hopefully this week. Thanks for posting.

**Comment by jluebker** [comment]
Cool thank you, no rush. I was just trying an alternate workflow to the SAT process I’ve been working with.

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by ksobon** [comment]
So far I have been able to narrow it down to an error that Dynamo throws: 

`StandardError: Unable to create face from spline : IG_SURFACE_IRREGULAR -- Irregular Surface` 

This looks to be a Dynamo limitation, but I want to find out what surface specifically causes that error and why would they flag it as "irregular", maybe there is something that we can do to "fix them" in Rhino. 

I will keep you in touch.

**Comment by jluebker** [comment]
I was thinking about this last night a bit. The geometry that fails is a torus I used the twist command on in rhino. I can try replicating it with an un-modified torus as well. Ironically though, the other two complex shapes also were modified with the twist command in rhino and they worked fine.

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by jluebker** [comment]
Ok it appears that a torus will work as does modifying a torus with anything but the twist command. It seems that the twist does something to a torus that throws the error you see and dynamo does not like it.

[cid:image001.jpg@01D167DE.837CF460]
[cid:image002.jpg@01D167DE.837CF460]

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by ksobon** [comment]
Ok, I am not sure how you created this, but that thing was nasty. It had self intersections that were throwing Dynamo off. I am usually pretty cool with people making funky shapes and trying to use them to "test" Mantis Shrimp, but dude this surface is a definition of how you should NOT model in Rhino. I don't see a point in trying to translate that to any other software. 

Still, I got it translated, but only after I re-created that one troublesome surface.

![image](https://cloud.githubusercontent.com/assets/529781/13057501/aab0c0e8-d3ea-11e5-9a42-68198fc21c55.png)

**Comment by ksobon** [comment]
BTW, the rest of them worked fine too. I did re-build the two twisted torus shapes but i don't think it was actually necessary. 

![image](https://cloud.githubusercontent.com/assets/529781/13057655/a36441b0-d3eb-11e5-8f1a-69f590f98c64.png)

**Comment by jluebker** [comment]
That’s actually not the one that fails in my graph… it’s the torus I used the twist command on in rhino. I know that surface has self-intersecting geometry and it was purposeful. I was fully trying to compare the capabilities of importing geometry into dynamo using mantis shrimp compared to the SAT option. I was purposefully trying to break it so I know the limits before I deploy this to the office as a stable way of importing rhino geometry into revit for those who do not understand the finer points of 3d modeling. I doubt any one will use a torus so I think we are ok they but I do some times see intersecting surfaces…

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by jluebker** [comment]
Interesting… ok good to know that rebuilding in rhino will fix this… thanks for looking into it and sorry for the hassle.

[cid:image002.jpg@01D167E0.4DDE6210]

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will
