### ISSUE TITLE
Unit comparison between Rhino <> Dynamo

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ksobon/MantisShrimp#2]
@ksobon looks like there is no check for units from the source document. It is probably a good idea to add one.

**Comment by ksobon** [comment]
OK, I just added units to DY>GH>DY transfers. For some reason it slowed down my graph execution in GH. I will test that further to make sure that it doesn't compromise speed too much. 
PS. On transfers between DY and GH i am assuming that DY side is always operating in Meters (DY uses meters internally) so I am only adjusting units to and from Meters.
