### ISSUE TITLE
null values in dynamo

### ISSUE THREAD

**Issue by javier-fqg** [ksobon/MantisShrimp#21]
Good Morning Konrad¡ I am triying to use the package but when I try to import geometry from Grasshopper to Dynamo all i get is a null value...If I do that with simple geometry like a sphere it works, but if I try with something a little bit more complex (a sphere that I have distort in rhino and take into grasshopper, later export to dynamo) it doesn´t work...I am using Dynamo 1.1 and the last version of grasshopper and rhinoceros...this package can import any kind of geometry? Thank u, if u need it i will upload the files of grasshopper and dynamo later¡

**Comment by javier-fqg** [comment]
[mantis shrimp.zip](https://github.com/ksobon/MantisShrimp/files/455235/mantis.shrimp.zip)

Konrad i upload the dynamo file and also the rhino file....If I try to export the grey shpere it works, but it doesn´t works when I try to export the red one (that is more complex) Do u know what can happens here? Thanks in advance¡

**Comment by javier-fqg** [comment]
@ksobon I think that I have find the solution....i have to rebuild the curve in rhino because if not i get null values....i have rebuilt it and now it works¡¡¡ Even from rhino or grasshopper, i have try both ways. I will keep testing the pacakge ;)

![imagen 1](https://cloud.githubusercontent.com/assets/21999094/18251874/1202d11e-738c-11e6-93dc-c8c38bf7ecba.jpg)
![imagen 2](https://cloud.githubusercontent.com/assets/21999094/18251875/122ac138-738c-11e6-9c4b-83c8a40e301b.jpg)

**Comment by ksobon** [comment]
Yeah, Dynamo and Revit are quite sensible about the Nurbs objects. I usually recommend rebuilding the nurbs to be degree 3. that seems to fix most of the issues.
