### ISSUE TITLE
Revit crashes when closing

### ISSUE THREAD

**Issue by ksobon** [ksobon/MantisShrimp#7]
@mostaphaRoudsari There is some sort of an issue that causes Revit to crash when you exit Revit file. It's not a critical bug since Revit crashes when you are closing the file and most likely after you saved your work but regardless its annoying. Also, rhinocommon throws an error on closing.

**Comment by ondejcik** [comment]
This happened to me  as well around that time, but i havent had installed mantis shrimp, so it might be related to some revit update
