### ISSUE TITLE
Export from dynamo does not work

### ISSUE THREAD

**Issue by ondejcik** [ksobon/MantisShrimp#8]
Hi, 

it looks like very interesting plug in, great work. I have little problem, exporting from grasshopper to dynamo is working fine for me, but from dynamo, it will not write new file. In watch panel i have only "null" ( if _export is set to true, otwerwise i ll get message to set to to true)

thanks for help

/Vladimir
![image](https://cloud.githubusercontent.com/assets/4834544/5755728/3e89aa44-9ca8-11e4-8a56-a9604684974f.png)

**Comment by ksobon** [comment]
The most common error is a missing path to rhinocommon.dll file. Can you
please check which location is your rhino installed? Also, to find out the
real error i would double click the "write gh file" and copy/paste the
python node contained inside. You can then plug in the geometry, path and
boolean just like into the "write gh file" node but you will get a yellow
error text and be able to better trouble shoot.

-konrad

On Thursday, January 15, 2015, ondejcik <notifications@github.com> wrote:

> Hi,
>
> it looks like very interesting plug in, great work. I have little problem,
> exporting from grasshopper to dynamo is working fine for me, but from
> dynamo, it will not write new file. In watch panel i have only "null" ( if
> _export is set to true, otwerwise i ll get message to set to to true)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4834544/5755728/3e89aa44-9ca8-11e4-8a56-a9604684974f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksobon/MantisShrimp/issues/8>.
>


-- 
Thank you, Konrad

**Comment by ondejcik** [comment]
hi,

so my error is this: Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 201, in <module>
  File "<string>", line 65, in process_list
TypeError: Point is not iterable


i have  rhino common here: C:\Program Files\Rhinoceros 5 (64-bit)\System

/Vladimir

**Comment by ondejcik** [comment]
i have the solution, what i was missing was to create list of that single point. (list.create node)

**Comment by ksobon** [comment]
Yes, I was going to say, that I anticipated input to be a list, even if it is just a single item. I will fix that, but great effort to come up with the solution on your own!
